# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI MOAR
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]


    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn setup
    - run: yarn build dev
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'dev_releasexxx.zip'
        #exclusions: '*.git* /*node_modules/* .editorconfig'
        #path

    - name: Publish Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest_potatox"
        prerelease: true
        title: "DEV Build yesxxx"
        files: |
          dev_releasexxx.zip     
